<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Villes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <script src="main.js"></script>
</head>
<body>
   
    <section action="villes.php" method ="GET">
        
        <h1>Villes du Département <?$numDept?></h1>
      
        
        <div>
             <table action="index.php" method ="GET">
              
                <thead>
                    
                    <th>Nom de la ville </th>
                    <th>Code postal</th>
              
            
                </thead>
                <tbody>
            
                    <?php foreach($result1 as $result1):?>
                    <tr>   
                      
                        <td><?=$result1['ville_nom']?></td>
                        <td><?=$result1['ville_code_postal']?> </td>
                
                    </tr> 
                    
                    <?php endforeach;?>
                </tbody>
            </table>

 
        </div>
        
      
    </section>
    


</body>
</html>